apiVersion: v1
kind: Service
metadata:
  name: {{ template "bk-hcm.fullname" . }}-woaserver
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  type: {{ .Values.woaserver.service.type }}
  ports:
    {{- with .Values.woaserver.service.ports }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  selector:
    {{- include "common.labels.matchLabels" . | nindent 4 }}
    component: woaserver
